site_name: AI Conventions
site_url: https://safurrier.github.io/cookiecutter-ai-conventions/
site_description: Cookiecutter template for creating AI development convention projects
site_author: safurrier

repo_name: safurrier/cookiecutter-ai-conventions
repo_url: https://github.com/safurrier/cookiecutter-ai-conventions
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - content.action.edit
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/library

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            merge_init_into_class: true
            docstring_style: google

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started.md
    - Quick Start: tutorials.md
    - Migration Guide: MIGRATION.md
  - User Guide:
    - Provider Setup: providers.md
    - Creating Domains: creating-domains.md
    - Configuration System: configuration-system.md
    - Textual TUI: textual-tui.md
  - Examples:
    - Migration Examples:
      - From .cursorrules: examples/migration-from-cursorrules.md
      - From Team Wiki: examples/migration-from-team-wiki.md
  - Reference:
    - CLI Commands: reference/cli.md
    - API Documentation: reference/api.md
    - Configuration: reference/configuration.md
  - Troubleshooting: troubleshooting.md
  - FAQ: FAQ.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/safurrier/cookiecutter-ai-conventions